[package]
name = "espstd"
version = "0.1.0"
authors = ["huonwe <howinee@gmail.com>"]
edition = "2021"
resolver = "2"

[profile.release]
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[features]
default = ["native"]
native = ["esp-idf-sys/native"]


[dependencies]
esp-idf-sys = { version = "0.32.1", features = ["binstart"] }
esp-idf-hal = { version = "0.40.1"}
esp-idf-svc = { version = "0.45.0"}
anyhow = "1.0.71"
embedded-hal = "0.2.7"
embedded-svc = '0.24.0'
wifi = {path = "lib/wifi"}

rgb = "=0.8.36"
rgb-led = {path = "lib/rgb-led"}

[build-dependencies]
embuild = "0.31.1"